In [ ]:
#1. Importe o pacote numpy com o nome np.
import numpy as np

In [ ]:
#2. Crie o seguinte vetor unidimensional (1D):
vetor = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
vetor

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#3. Qual é o comprimento len do vetor?
len(vetor)

10

In [ ]:
#4. Quantas dimensões ndim o vetor possui?
np.ndim(vetor)

1

In [ ]:
#5. O que a função shape retorna?
np.shape(vetor)

(10,)

In [ ]:
#6. Crie a variável pares e extraia todos os números pares do vetor para ela:
vetorpar = np.arange(0, 9, 2)
print(vetorpar)

[0 2 4 6 8]


In [ ]:
#7. Substitua todos os elementos ímpares do vetor por -1, em seguida, ordene os resultados:
vetorimpar = np.arange(1, 9, 2)-1
print(vetorimpar)

[0 2 4 6]


In [ ]:
#8. Converta o vetor unidimensional (1D) abaixo para uma matriz (2D) com 4 linhas. Dica: reshape
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.reshape(x, (2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
#9. Obtenha os itens em comum, ou seja, a intersecção dos vetores a e b abaixo:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([2, 4, 6, 8, 10])
c = []

In [ ]:
for i in a:
  for j in b:
    if j == i:
      c.append(j)
print(c)

[2, 4, 6]


In [ ]:
#10. Retorne os valores únicos do vetor a que não estão no vetor b (diferença)
a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 6, 8, 10])
c = []

In [ ]:
for i in a:
  for j in b:
    if j != i:
      c.append(j)
print(c)

[2, 4, 6, 8, 10, 4, 6, 8, 10, 2, 4, 6, 8, 10, 2, 6, 8, 10]


In [17]:
#11. Retorne um vetor com as posições (índices) onde os elementos do vetor a sãos iguais aos elementos do vetor b. Dica: where.
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([2, 4, 3, 4, 10, 6])

indices = np.where(a == b)
indices

(array([2, 3, 5]),)

In [18]:
#12. Obtenha todos os itens entre 5 e 15 do vetor a = [0, 1, 2, 3, . . ., 20].
a = np.arange(21)
interval = np.logical_and(a >= 5, a <= 15)
a[interval]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
#13. Crie e imprima um vetor com 5 números aleatórios, sem seguida, obtenha os valores máximo e mínimo dele e mostre na tela.
rand = np.random.randint(1, 100, 5)
print(f'Vetor de 5 números aleatórios: {rand}')
print(f'\n- Maior valor do vetor: {rand.max()}')
print(f'- Menor valor do vetor: {rand.min()}')

Vetor de 5 números aleatórios: [88 33  8 23 23]

- Maior valor do vetor: 88
- Menor valor do vetor: 8


In [22]:
#14. Crie a seguinte matriz:
matriz = np.array([[7,8,9],[4,5,6], [1,2,3]])
matriz

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [21]:
#15. Troque de lugar a primeira coluna com a útltima coluna da matriz.
matrizCopy = matriz.copy()
matriz[:,0] = matrizCopy[:,-1]
matriz[:,-1] = matrizCopy[:,0]

matriz

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [23]:
#16. Troque de lugar a primeira linha com a útltima linha da matriz.
matrizCopy = matriz.copy()
matriz[0,:] = matrizCopy[-1,:]
matriz[-1,:] = matrizCopy[0,:]

matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#17. Crie uma matriz 7 × 5 preenchida com números decimais aleatórios entre 1 e 5.
values = []
for i in range(7):
    values.append(np.random.uniform(0.0, 5.0, (5,)))

randomMatriz = np.array(values)
randomMatriz

array([[3.00333115, 3.87896412, 0.65306418, 3.01377777, 3.41753325],
       [1.5595602 , 3.90012703, 4.14667497, 0.78330128, 2.49835029],
       [0.68408875, 2.14397274, 0.15946042, 3.47735939, 2.59311974],
       [2.90450319, 3.64062571, 3.74786648, 1.173523  , 3.08182458],
       [4.66851433, 2.92697974, 4.99182868, 2.0571838 , 0.48471565],
       [4.78989538, 4.45029866, 3.00634038, 1.34929528, 4.69258379],
       [4.45681329, 1.08987223, 1.02853229, 4.9224355 , 0.12410532]])

In [25]:
#18. Qual é o comprimento len da matriz?
len(randomMatriz)

7

In [26]:
#19. Quantas dimensões ndim a matriz possui?
np.ndim(randomMatriz)

2

In [27]:
#20. O que a função shape retorna?
np.shape(randomMatriz)

(7, 5)